blueapi:
  hostNetwork: false
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 100Mi
  ingress:
    create: false
    host: ckk43848.diamond.ac.uk
  
  worker:
    env:
      metadata:
         instrument: ckk43848
         # instrument_session: 
      sources:
      - kind: planFunctions
        module: dodal.plans
      events:
        broadcast_status_events: false
    stomp:
      auth:
        username: guest
        password: guest
      host: ckk43848-rabbitmq-daq.diamond.ac.uk
      enabled: false
    logging:
      level: "INFO"
      graylog:
        enabled: false
        url: http://graylog-log-target.diamond.ac.uk:12231/
    oidc:
     well_known_url: "https://authn.diamond.ac.uk/realms/master/.well-known/openid-configuration"
     client_id: "blueapi-cli"
    scratch:
      root: /dls_sw/ckk43848/software/blueapi/scratch
      repositories:
        - name: dodal
          remote_url: https://github.com/DiamondLightSource/dodal.git
  initContainer:
    enabled: false

oauth2:
  proxyVarsAsSecrets: false
  extraEnv:
    - name: OAUTH2_PROXY_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: blueapi-secret
          key: client-secret
    - name: OAUTH2_PROXY_COOKIE_SECRET
      valueFrom:
        secretKeyRef:
          name: blueapi-secret
          key: cookie-secret
  config:
    configFile: |-
      skip_provider_button = true
      skip_jwt_bearer_tokens = true
      cookie_refresh="1m"
      cookie_expire="30m"
      email_domains = [ "*" ]
      skip_auth_routes=[
      "GET=^/config/oidc",
      "GET=^/healthz"
      ]
  ingress:
    enabled: true
    hosts:
      - ckk43848.diamond.ac.uk
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    path: /
    pathType: Prefix
  alphaConfig:
    enabled: true
    configData:
      upstreamConfig:
        proxyRawPath: true
        upstreams:
          - id: blueapi
            path: /
            uri: http://ckk43848-blueapi
      providers:
        - provider: oidc
          id: authn.diamond.ac.uk
          clientID: blueapi
          clientSecret: ${OAUTH2_PROXY_CLIENT_SECRET}
          oidcConfig:
            insecureAllowUnverifiedEmail: true
            emailClaim: sub
            audienceClaims: ["aud"]
            issuerURL: https://authn.diamond.ac.uk/realms/master
      injectRequestHeaders:
        - name: Authorization
          values:
            - claim: access_token
              prefix: "Bearer "